name: Nodejs Deploy Lightsailc

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: SCP deploy action
      uses: appleboy/ssh-action@master
      with:
        scr: .
        host: 54.221.5.196
        remote: /home/ubuntu/sws_eduzzwebhook
        port: 22
        user: ubuntu
        key: ${{ secrets.KEY }}
