name: Nodejs Deploy Lightsail

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Copy file via ssh
      uses: appleboy/scp-action@v0.0.1
      env:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PASSPHRSE }}
        port: ${{ secrets.PORT }}
        source: "."
        target: "/opt/nodeserver"
    
    - name: Executing remore command
      uses: appleboy/ssd-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.PASSPHRSE }}
        script: cat /opt/nodeserver/server.js
