name: Nodejs Deploy Lightsailc

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: SCP deploy action
      uses: nogsantos/ssh-scp-deploy@v1.2.1
      with:
        src: .
        host: 54.221.5.196
        remote: /home/ubuntu/sws_eduzzwebhook
        port: 22
        user: ubuntu
        key: ${{ secrets.KEY_RSA }}
