name: MasterCI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    
    steps:
      - uses: actions/checkout@master
      
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./*
          host: 54.221.5.196
          remote: /home/ubuntu/sws_eduzzwebhook
          port: 22
          user: ubuntu
          key: ${{ secrets.KEY_RSA }}
