name: Nodejs Deploy Lightsail

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Copy file via ssh
      uses: appleboy/scp-action@master
      with:
        host: 54.221.5.196
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        source: "."
        target: "/opt/nodeserver"
