name: Nodejs Deploy Lightsailr

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Copy file via ssh2
      uses: appleboy/scp-action@master
      env:
        host: 54.221.5.196
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
      with:
        source: "."
        target: "/home/ubuntu/sws_eduzzwebhook"
