name: MasterCI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    
    steps:
      - uses: actions/checkout@master
      
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./*
          host: 54.221.5.196
          remote: /opt/sws_eduzzwebhook
          port: 22
          user: ubuntu
          key: ${{ secrets.KEY_RSA }}
          
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: 54.221.5.196
          username: ubuntu
          key: ${{ secrets.KEY_RSA }}
          port: 22
          script: sudo systemctl restart swswebhook
