name: Build and Deploy

on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node 12
        uses: actions/setup-node@v2.1.0
      
      - name: Install Node.js Dependencies
        run: npm install
        
      - run: npm fun build
